### ISSUE TITLE
Error: 'Pandas' object has no attribute 'exp_annotation"

### ISSUE THREAD

**Issue by msing21** [bio-ontology-research-group/deepgoplus#26]
I am trying to run predict.sh code but it is giving me the error that 'Pandas' object has no attribute 'exp_annotation'. What should I do now?

**Comment by coolmaksat** [comment]
Could you please try to install deepgoplus with pip. I updated the readme now.

**Comment by msing21** [comment]
Thanks a lot for replying. I am going to try and let u know.

Thanks
Manali Singha
________________________________

**Comment by msing21** [comment]
(my_deepgo) [msing21@smic374 msing21]$ deepgoplus --data-root /work/msing21/data/ --in-file test.fasta 
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/msing21/.conda/envs/my_deepgo/bin/deepgoplus", line 11, in <module>
    sys.exit(main())
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/msing21/.conda/envs/my_deepgo/lib/python3.6/site-packages/deepgoplus/main.py", line 69, in main
    annotations[row.proteins] = set(row.exp_annotations)
AttributeError: 'Pandas' object has no attribute 'exp_annotations'

After using all your updated information from the readme I got the same error.

**Comment by msing21** [comment]
(my_deepgo) [msing21@smic374 msing21]$ deepgoplus --data-root /work/msing21/data/ --in-file test.fasta 
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/msing21/.conda/envs/my_deepgo/bin/deepgoplus", line 11, in <module>
    sys.exit(main())
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/msing21/.conda/envs/my_deepgo/lib/python3.6/site-packages/deepgoplus/main.py", line 69, in main
    annotations[row.proteins] = set(row.exp_annotations)
AttributeError: 'Pandas' object has no attribute 'exp_annotations'

After using all your updated information from the readme I got the same error.

**Comment by msing21** [comment]
(my_deepgo) [msing21@smic374 msing21]$ deepgoplus --data-root /work/msing21/data/ --in-file test.fasta 
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/msing21/.conda/envs/my_deepgo/bin/deepgoplus", line 11, in <module>
    sys.exit(main())
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/msing21/.conda/envs/my_deepgo/lib/python3.6/site-packages/deepgoplus/main.py", line 69, in main
    annotations[row.proteins] = set(row.exp_annotations)
AttributeError: 'Pandas' object has no attribute 'exp_annotations'

After using all your updated information from the readme I got the same error.

**Comment by msing21** [comment]
(my_deepgo) [msing21@smic374 msing21]$ deepgoplus --data-root /work/msing21/data/ --in-file test.fasta 
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/msing21/.conda/envs/my_deepgo/bin/deepgoplus", line 11, in <module>
    sys.exit(main())
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/msing21/.conda/envs/my_deepgo/lib/python3.6/site-packages/deepgoplus/main.py", line 69, in main
    annotations[row.proteins] = set(row.exp_annotations)
AttributeError: 'Pandas' object has no attribute 'exp_annotations'

After using all your updated information from the readme I got the same error.

**Comment by msing21** [comment]
After using all your updated information from the readme I got the same error.

(my_deepgo) [msing21@smic374 msing21]$ deepgoplus --data-root /work/msing21/data/ --in-file test.fasta
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/msing21/.conda/envs/my_deepgo/bin/deepgoplus", line 11, in <module>
    sys.exit(main())
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/msing21/.conda/envs/my_deepgo/lib/python3.6/site-packages/deepgoplus/main.py", line 69, in main
    annotations[row.proteins] = set(row.exp_annotations)
AttributeError: 'Pandas' object has no attribute 'exp_annotations'



________________________________

**Comment by coolmaksat** [comment]
Please download the data file again from here http://deepgoplus.bio2vec.net/data/data.tar.gz

**Comment by msing21** [comment]
I downloaded again the data from your given link and I ran the code and I found the another issue

deepgoplus --data-root /work/msing21/data/ --in-file test.fasta 
Using TensorFlow backend.
diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 20
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: /work/msing21/data
Opening the database...  [0.003939s]
#Target sequences to report alignments for: 25
Opening the input file...  [0.010561s]
Opening the output file...  [0.000974s]
Loading query sequences...  [5.7e-05s]
Masking queries...  [0.001525s]
Building query seed set...  [0.000105s]
Algorithm: Query-indexed
Building query histograms...  [0.000595s]
Allocating buffers...  [2.4e-05s]
Loading reference sequences...  [0.058464s]
Building reference histograms...  [0.007154s]
Allocating buffers...  [3e-05s]
Initializing temporary storage...  [0.420235s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [0.01216s]
Building query index...  [0.002149s]
Building seed filter...  [0.001397s]
Searching alignments...  [0.007412s]
Deallocating buffers...  [0.000256s]
Computing alignments...  [0.068882s]
Deallocating reference...  [0.000256s]
Loading reference sequences...  [5.1e-05s]
Deallocating buffers...  [1.3e-05s]
Deallocating queries...  [2.4e-05s]
Loading query sequences...  [2.9e-05s]
Closing the input file...  [0.00013s]
Closing the output file...  [0.000925s]
Closing the database file...  [0.000211s]
Deallocating taxonomy...  [2e-06s]
Total time = 0.602518s
Reported 6 pairwise alignments, 6 HSPs.
1 queries aligned.
Traceback (most recent call last):
  File "/home/msing21/.conda/envs/my_deepgo/bin/deepgoplus", line 11, in <module>
    sys.exit(main())
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/msing21/.conda/envs/my_deepgo/lib/python3.6/site-packages/deepgoplus/main.py", line 110, in main
    model = load_model(model_file)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/keras/models.py", line 239, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/keras/models.py", line 313, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/keras/layers/__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 139, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/keras/engine/topology.py", line 2487, in from_config
    process_layer(layer_data)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/keras/engine/topology.py", line 2473, in process_layer
    custom_objects=custom_objects)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/keras/layers/__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 141, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/keras/engine/topology.py", line 1252, in from_config
    return cls(**config)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/packages/python/3.6.2-anaconda/lib/python3.6/site-packages/keras/layers/convolutional.py", line 333, in __init__
    **kwargs)
TypeError: __init__() got multiple values for keyword argument 'data_format'

**Comment by coolmaksat** [comment]
This seems to be related to the tensorflow version, which version are you using?

**Comment by msing21** [comment]
I am using 1.2.0-rc2 version of tensor flow

**Comment by coolmaksat** [comment]
you need 1.12.0
