### ISSUE TITLE
predict.py - gzip fails to open ASCII file

### ISSUE THREAD

**Issue by hdetering** [bio-ontology-research-group/deepgoplus#46]
Hi,

in predict.py you open the DIAMOND output table using gzip, which leads to an error in current Python versions:
https://github.com/bio-ontology-research-group/deepgoplus/blob/585d9c56d3797a22f4934f8b4b10035d955bed35/predict.py#L44

The output I got with the example file `data/test_diamond.res` contained in your [data bundle](https://deepgo.cbrc.kaust.edu.sa/data/data-1.0.8.tar.gz) was this:
```
2022-06-28 14:53:36.462111: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "../tools/deepgoplus//predict.py", line 174, in <module>
    main()
  File "/home/hdetering/miniconda3/envs/crowdgo/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/hdetering/miniconda3/envs/crowdgo/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/hdetering/miniconda3/envs/crowdgo/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hdetering/miniconda3/envs/crowdgo/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "../tools/deepgoplus//predict.py", line 45, in main
    for line in f:
  File "/home/hdetering/miniconda3/envs/crowdgo/lib/python3.7/gzip.py", line 300, in read1
    return self._buffer.read1(size)
  File "/home/hdetering/miniconda3/envs/crowdgo/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/hdetering/miniconda3/envs/crowdgo/lib/python3.7/gzip.py", line 474, in read
    if not self._read_gzip_header():
  File "/home/hdetering/miniconda3/envs/crowdgo/lib/python3.7/gzip.py", line 422, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'AC')
``

**Comment by hdetering** [comment]
Oh, and the same happens when opening the FASTA file:
https://github.com/bio-ontology-research-group/deepgoplus/blob/585d9c56d3797a22f4934f8b4b10035d955bed35/predict.py#L132

**Comment by zjxhahaha** [comment]
Hi,I met this question too,Did you solve it?

**Comment by hdetering** [comment]
Well, I just edited the code to remove the `gzip.`.
Just a workaround, that's why I posted the Issue so that the devs can hopefully fix it in a future release.
