### ISSUE TITLE
Can't install DeepGOPlus dependencies

### ISSUE THREAD

**Issue by queirozhanna** [bio-ontology-research-group/deepgoplus#63]
Hi!

I've installed the majority of the required packages, but I'm facing errors installing word2vec. I've tried "conda install word2vec==0.10.2", "pip install word2vec==0.10.2" and "python3 -m pip install word2vec==0.10.2" but neither of these work.

When I try to install by conda, I receive this message:
`$ conda install word2vec==0.10.2
Channels:
 - conda-forge
 - defaults
 - bioconda
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - word2vec==0.10.2

Current channels:

  - https://conda.anaconda.org/conda-forge
  - defaults
  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.`

and when I try to install by pip install or python3 - m pip install, I receive this:
`pip install word2vec==0.10.2
Defaulting to user installation because normal site-packages is not writeable
Collecting word2vec==0.10.2
  Using cached word2vec-0.10.2.tar.gz (60 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-o6469j0x/word2vec_6a08e0e29b6e402db3c30ef993ccb849/setup.py", line 102, in <module>
          ext_modules=cythonize("word2vec/word2vec_noop.pyx"),
        File "/home/queirozhanna/.local/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1008, in cythonize
          ctx = Context.from_options(c_options)
        File "/home/queirozhanna/.local/lib/python3.10/site-packages/Cython/Compiler/Main.py", line 100, in from_options
          return cls(options.include_path, options.compiler_directives,
        File "/home/queirozhanna/.local/lib/python3.10/site-packages/Cython/Compiler/Main.py", line 78, in __init__
          from . import Builtin, CythonScope
        File "/home/queirozhanna/.local/lib/python3.10/site-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
          from .UtilityCode import CythonUtilityCode
        File "/home/queirozhanna/.local/lib/python3.10/site-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
          from .TreeFragment import parse_from_strings, StringParseContext
        File "/home/queirozhanna/.local/lib/python3.10/site-packages/Cython/Compiler/TreeFragment.py", line 17, in <module>
          from .Visitor import VisitorTransform
        File "Cython/Compiler/Visitor.py", line 16, in init Cython.Compiler.Visitor
        File "/home/queirozhanna/.local/lib/python3.10/site-packages/Cython/Compiler/Nodes.py", line 33, in <module>
          from .Pythran import has_np_pythran, pythran_type, is_pythran_buffer
        File "/home/queirozhanna/.local/lib/python3.10/site-packages/Cython/Compiler/Pythran.py", line 10, in <module>
          import pythran
        File "/usr/lib/python3/dist-packages/pythran/__init__.py", line 41, in <module>
          from pythran.toolchain import (generate_cxx, compile_cxxfile, compile_cxxcode,
        File "/usr/lib/python3/dist-packages/pythran/toolchain.py", line 6, in <module>
          from pythran.backend import Cxx, Python
        File "/usr/lib/python3/dist-packages/pythran/backend.py", line 7, in <module>
          from pythran.analyses import LocalNodeDeclarations, GlobalDeclarations, Scope
        File "/usr/lib/python3/dist-packages/pythran/analyses/__init__.py", line 12, in <module>
          from .aliases import Aliases, StrictAliases
        File "/usr/lib/python3/dist-packages/pythran/analyses/aliases.py", line 6, in <module>
          from pythran.syntax import PythranSyntaxError
        File "/usr/lib/python3/dist-packages/pythran/syntax.py", line 7, in <module>
          from pythran.tables import MODULES
        File "/usr/lib/python3/dist-packages/pythran/tables.py", line 174, in <module>
          BINARY_UFUNC = {"accumulate": FunctionIntr()}
        File "/usr/lib/python3/dist-packages/pythran/intrinsic.py", line 101, in __init__
          super(FunctionIntr, self).__init__(**kwargs)
        File "/usr/lib/python3/dist-packages/pythran/intrinsic.py", line 58, in __init__
          self.args = ast.arguments(
        File "/home/queirozhanna/.local/lib/python3.10/site-packages/gast/gast.py", line 10, in create_node
          assert nbparam in (0, len(Fields)), \
      AssertionError: Bad argument number for arguments: 7, expecting 6
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

Without word2vec==0.10.2, I can't install DeepGOPlus, which is necessary to my work 😔

**Comment by coolmaksat** [comment]
Hi,
Which version of python are you using? Please use python3.7.
I don't see word2vec requirement in https://github.com/bio-ontology-research-group/deepgoplus/blob/master/requirements.txt. I would recommend installing the dependencies with pip

**Comment by remkv6** [comment]
I created a tutorial for deepgoplus that shows how I installed and ran the software here. Perhaps it will be helpful
https://bioinformaticsworkbook.org/dataAnalysis/GenomeAnnotation/DeepGoPlus_AI_Functional_Prediction_of_Proteins.html#gsc.tab=0

**Comment by coolmaksat** [comment]
Thank you. Great work!
