### ISSUE TITLE
Try to run 'evaluate_deepgoplus.py' with cafa data

### ISSUE THREAD

**Issue by asangphukieo** [bio-ontology-research-group/deepgoplus#9]
I try to run 'evaluate_deepgoplus.py' with existing cafa model in data-cafa folder
I got this message

Error message:

Traceback (most recent call last):
  File "evaluate_deepgoplus.py", line 257, in <module>
    main()
  File "/home/asangphukieo/Documents/anaconda2/envs/deepgo/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/asangphukieo/Documents/anaconda2/envs/deepgo/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/asangphukieo/Documents/anaconda2/envs/deepgo/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/asangphukieo/Documents/anaconda2/envs/deepgo/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "evaluate_deepgoplus.py", line 115, in main
    for j, score in enumerate(row.preds):
AttributeError: 'Pandas' object has no attribute 'preds'

Also, I can run cafa3_data.py and deepgoplus.py, but I cannot get prediction result from deepgoplus.py.

Thanks,
Apiwat

**Comment by coolmaksat** [comment]
Hi,
Thank you for reporting this.
I updated data-cafa.tar.gz file. Please download latest version which includes predictions.pkl file with prediction scores.
Alternatively, you can run `python deepgoplus.py -ld`. It will load trained model and generate predictions.pkl file

Let me know if you have any other questions.

**Comment by asangphukieo** [comment]
Thank you for prompt reply,

I run python deepgoplus.py with -ld option, but I got a new error,

Traceback (most recent call last):
  File "deepgoplus.py", line 271, in <module>
    main()
  File "/home/asangphukieo/Documents/anaconda2/envs/deepgo/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/asangphukieo/Documents/anaconda2/envs/deepgo/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/asangphukieo/Documents/anaconda2/envs/deepgo/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/asangphukieo/Documents/anaconda2/envs/deepgo/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "deepgoplus.py", line 155, in main
    valid_generator.reset()
UnboundLocalError: local variable 'valid_generator' referenced before assignment
